"""empty message

Revision ID: 19a1ffcd05fd
Revises: 8c00c36da9f9
Create Date: 2023-09-13 15:56:48.333563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19a1ffcd05fd'
down_revision = '8c00c36da9f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bats', schema=None) as batch_op:
        batch_op.alter_column('player_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bats', schema=None) as batch_op:
        batch_op.alter_column('player_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
